/*
 DO NOT EDIT MANUALLY !!!
 Generated by scripts\trans_gen.py
*/

#ifndef MAKELANGID
#include <windows.h>
#endif

int gTranslationsCount = 8;

const WCHAR * const gTranslations[] = {
  /* Translations for language en */
  L"%s of %s",
  L"Error: Couldn't run ZeroView!",
  L"Error: ZeroView hasn't been found!",
  L"Error: The document couldn't be downloaded!",
  L"GB",
  L"KB",
  L"MB",
  L"Opening document in ZeroView...",

  /* Translations for language sq */
  L"%s nga %s",
  L"Gabim: Nuk mund të hapë ZeroView!",
  L"Gabim: Nuk u gjet ZeroView!",
  L"Gabim: Nuk mund të shkarkohet dokumenti!",
  NULL,
  NULL,
  NULL,
  L"Hap dokumentin në ZeroView...",

  /* Translations for language ar */
  L"%s من %s",
  L"خطأ: لم أتمكن من تشغيل البرنامج",
  L"خطأ: البرنامج غير موجود",
  L"خطأ: لم أتمكن من تحميل الملف",
  L"ج.ب",
  L"ك.ب",
  L"م.ب",
  L"فتح الملف في ZeroView...",

  /* Translations for language am */
  L"%s՝ %s-ից",
  L"Սխալ. Հնարավոր չէ բացել ZeroView-ը:",
  L"Սխալ. ZeroView-ը չի գտնվել:",
  L"Սխալ. Փաստաթուղթը չի կարող բեռնվել:",
  L"ԳԲ",
  L"ԿԲ",
  L"ՄԲ",
  L"Փաստաթուղթը բացվում է ZeroView-ով...",

  /* Translations for language az */
  L"%s/%s",
  L"Xəta: ZeroView işə salına bilmədi!",
  L"Xəta: ZeroView tapılmadı!",
  L"Xəta: Sənədi endirmək mümkün olmadı!",
  NULL,
  NULL,
  NULL,
  L"Sənəd ZeroView-də açılır...",

  /* Translations for language eu */
  L"%s -> %s-tik",
  L"Akatsa: Ezinezkoa ZeroView abiaraztea!",
  L"Akatsa: ZeroView ez da aurkitu!",
  L"Akatsa: Agiria ezin da jeitsi!",
  NULL,
  NULL,
  NULL,
  L"Agiria irekitzen ZeroView-an...",

  /* Translations for language ca */
  L"%s de %s",
  L"Error: no es pot executar el ZeroView!",
  L"S'ha produït un error: no es troba el ZeroView!",
  L"Error: no es pot baixar el document!",
  NULL,
  NULL,
  NULL,
  L"S'està obrint el document al ZeroView...",

  /* Translations for language ca-xv */
  L"%s de %s",
  L"Error: no es pot executar el ZeroView!",
  L"S'ha produït un error: no es troba el ZeroView!",
  L"Error: no es pot baixar el document!",
  NULL,
  NULL,
  NULL,
  L"S'està obrint el document al ZeroView...",

  /* Translations for language cn */
  NULL,
  L"错误：无法运行ZeroView!",
  L"失败: 找不到ZeroView",
  L"错误： 文档无法下载!",
  NULL,
  NULL,
  NULL,
  L"正在用ZeroView打开文件...",

  /* Translations for language tw */
  NULL,
  L"錯誤：無法運行 ZeroView!",
  L"錯誤：找不到 ZeroView",
  L"錯誤：無法下載文件！",
  NULL,
  NULL,
  NULL,
  L"以 ZeroView 開啟文件...",

  /* Translations for language hr */
  L"%s od %s",
  L"Greška: Nemoguće pokrenuti ZeroView",
  L"Greška: ZeroView nije pronađena",
  L"Greška: Dokument nije moguće preuzeti!",
  L"GiB",
  L"KiB",
  L"MiB",
  L"Otvaranje dokumenta u ZeroView...",

  /* Translations for language cz */
  L"%s z %s",
  L"Chyba: Nepodařilo se spustit ZeroView!",
  L"Chyba: Program ZeroView nebyl nalezen!",
  L"Chyba: Stažení dokumentu se nezdařilo!",
  NULL,
  NULL,
  NULL,
  L"Otevírat dokumenty v ZeroView...",

  /* Translations for language dk */
  L"%s af %s",
  L"Fejl: Kan ikke køre ZeroView !",
  L"Fejl: ZeroView ikke fundet !",
  L"Fejl: Dokumentet kunne ikke hentes !",
  L"Gb",
  L"Kb",
  L"Mb",
  L"Åben dokument i ZeroView ...",

  /* Translations for language nl */
  L"%s van %s",
  L"Fout: kon ZeroView niet uitvoeren!",
  L"Fout: ZeroView werd niet gevonden!",
  L"Fout: het document kon niet gedownload worden!",
  NULL,
  NULL,
  NULL,
  L"Document in ZeroView aan het openen...",

  /* Translations for language et */
  L"%s, kokku %s",
  L"Viga: Ei suudetud käivitada rakendust ZeroView!",
  L"Viga: Ei leitud rakendust ZeroView",
  L"Viga: Dokumenti ei suudetud alla laadida!",
  NULL,
  L"kB",
  NULL,
  L"Dokumendi avamine rakenduses ZeroView...",

  /* Translations for language fi */
  L"%s / %s",
  L"Virhe: ZeroView:n käynnistäminen epäonnistui!",
  L"Virhe: ZeroView ei löytynyt!",
  L"Virhe: tiedoston lataaminen epäonnistui!",
  L"Gt",
  L"Kt",
  L"Mt",
  L"Avataan asiakirjaa ZeroView:ssä...",

  /* Translations for language fr */
  L"%s de %s",
  L"Erreur : impossible de lancer ZeroView !",
  L"Erreur : ZeroView non trouvé !",
  L"Erreur : le document n'a pu être téléchargé !",
  L"Go",
  L"Ko",
  L"Mo",
  L"Ouverture du document dans ZeroView…",

  /* Translations for language de */
  L"%s von %s",
  L"Fehler: Konnte ZeroView nicht ausführen!",
  L"Fehler: ZeroView ist unaufindbar!",
  L"Fehler: Das Dokument konnte nicht heruntergeladen werden!",
  NULL,
  NULL,
  NULL,
  L"Das Dokument wird in ZeroView geöffnet…",

  /* Translations for language hu */
  L"%s/%s",
  L"Hiba: ZeroView futtatása sikertelen!",
  L"Hiba: ZeroView nem található!",
  L"Hiba: a dokumentum letöltése sikertelen!",
  L"Gb",
  L"Kb",
  L"Mb",
  L"Dokumentum megnyitása ZeroView-ben...",

  /* Translations for language id */
  L"%s dari %s",
  L"Kesalahan: Tidak bisa menjalankan ZeroView.",
  L"Kesalahan: ZeroView tidak ditemukan.",
  L"Kesalahan: file tidak dapat diunduh.",
  NULL,
  NULL,
  NULL,
  L"Membuka dokumen menggunakan ZeroView",

  /* Translations for language it */
  L"%s di %s",
  L"Errore. Impossibile eseguire ZeroView!",
  L"Errore. ZeroView non trovato!",
  L"Errore. Il documento non può essere scaricato!",
  NULL,
  NULL,
  NULL,
  L"Apri documento in ZeroView...",

  /* Translations for language ja */
  L"%s 中 %s",
  L"エラー: ZeroView を実行できませんでした！",
  L"エラー: ZeroView が見つかりませんでした！",
  L"エラー: ドキュメントをダウンロードできませんでした！",
  NULL,
  NULL,
  NULL,
  L"ZeroView でドキュメントを開いています…",

  /* Translations for language kr */
  L"%s / %s",
  L"오류: ZeroView를 실행할 수 없습니다!",
  L"오류: ZeroView를 찾을 수 없습니다!",
  L"오류: 문서를 다운로드할 수 없습니다!",
  NULL,
  NULL,
  NULL,
  L"ZeroView로 문서 여는 중...",

  /* Translations for language ku */
  L"%s لە %s",
  L"!بکرێتەوە ZeroView هەڵە: ناتوانرێت",
  L"هەڵە: ZeroView نەدۆزرایەوە!",
  L"!هەڵە: بەڵگەنامە ناتوانرێت دابگیرێت",
  L"گێگابایت",
  L"کیلۆبایت",
  L"مێگابایت",
  L"...ZeroView کردنەوەی بەڵگەنامەکان بەهۆی",

  /* Translations for language mk */
  L"%s од %s",
  L"Грешка: ZeroView не може да се изврши!",
  L"Грешка: ZeroView не постои!",
  L"Грешка: Документот не може да се преземе!",
  NULL,
  NULL,
  NULL,
  L"Го отворам документот во ZeroView...",

  /* Translations for language fa */
  NULL,
  L"ZeroView pdf خطا: عدم توانایی در اجرای",
  L"خطا :ZeroView pdf پیدا نشد",
  L"خطا : عدم توانایی در دانلود متن",
  L"گیگابایت",
  L"کیلوبایت",
  L"مگابایت",
  L"ZeroView pdf باز کردن متن در",

  /* Translations for language pl */
  L"%s z %s",
  L"Błąd: nie można uruchomić ZeroView",
  L"Błąd: nie znaleziono ZeroView",
  L"Błąd: nie można pobrać dokumentu!",
  NULL,
  NULL,
  NULL,
  L"Otwieranie dokumentu w ZeroView...",

  /* Translations for language br */
  L"%s de %s",
  L"Não foi possível rodar o ZeroView!",
  L"O ZeroView não foi encontrado!",
  L"Erro: o documento não pôde ser baixado!",
  NULL,
  NULL,
  NULL,
  L"Abrindo documento no ZeroView...",

  /* Translations for language pt */
  L"%s de %s",
  L"Erro: não foi possível iniciar o ZeroView!",
  L"Erro: o ZeroView não foi encontrado!",
  L"Erro: não foi possível transferir o documento!",
  NULL,
  NULL,
  NULL,
  L"Abrir documento no ZeroView",

  /* Translations for language ro */
  L"%s din %s",
  L"Eroare: Nu s-a putut porni ZeroView PDF!",
  L"Eroare: ZeroView nu a fost gasit!",
  L"Eroare: Documentul nu s-a putut descarca!",
  NULL,
  NULL,
  NULL,
  L"Deschidere document in ZeroView...",

  /* Translations for language ru */
  L"%s из %s",
  L"Ошибка: не удалось запустить ZeroView!",
  L"Ошибка: ZeroView не найдена!",
  L"Ошибка: не удалось загрузить документ!",
  L"Гб",
  L"Кб",
  L"Мб",
  L"Открытие документа в ZeroView...",

  /* Translations for language sk */
  L"%s z %s",
  L"Chyba: Nie je možné spustiť ZeroView!",
  L"Chyba: Program ZeroView nebol nájdený!",
  L"Chyba: Stiahnutie súboru sa nepodarilo!",
  NULL,
  NULL,
  NULL,
  L"Otvárať dokument v ZeroView...",

  /* Translations for language es */
  L"%s de %s",
  L"Error: ¡No se pudo ejecutar ZeroView!",
  L"Error: ¡ZeroView no ha sido encontrado!",
  L"Error: ¡El documento no pudo ser descargado!",
  NULL,
  NULL,
  NULL,
  L"Abriendo documento en ZeroView...",

  /* Translations for language sv */
  L"%s av %s",
  L"Fel: Kunde inte starta ZeroView!",
  L"Fel: Hittade inte ZeroView!",
  L"Fel: Dokumentet kunde inte laddas ner!",
  NULL,
  NULL,
  NULL,
  L"Öppnar dokumentet med ZeroView...",

  /* Translations for language ta */
  L"%s ல் %s",
  L"சுமத்ரா PDFஐ இயங்கவில்லை",
  L"சுமத்ராPDF காணவில்லை",
  L"பிழை: கோப்பை பதிவிறக்கம் செய்ய முடியவில்லை",
  L"ஜிகா பைட்டு",
  NULL,
  NULL,
  L"கோப்பு சுமத்ரா PDFல் திறக்கப்படுகிறது..",

  /* Translations for language tr */
  L"%s ın %s ı",
  L"Hata: ZeroView çalıştırılamadı!",
  L"Hata: ZeroView bulunamadı!",
  L"Hata: Belge indirilemedi!",
  NULL,
  NULL,
  NULL,
  L"Belge ZeroView ile açılıyor...",

  /* Translations for language uk */
  L"%s із %s",
  L"Помилка: не вдалося запустити ZeroView",
  L"Помилка: ZeroView не було знайдено",
  L"Помилка: Неможливо завантажити документ!",
  NULL,
  NULL,
  NULL,
  L"Триває відкриття документа у ZeroView...",

  /* Translations for language uz */
  L"%s %s'dan",
  L"Xato: ZeroView ishga tushirib bo'lmadi!",
  L"Xato: ZeroView topilmadi!",
  L"Xato: hujjatni yuklab bo'lmadi!",
  NULL,
  NULL,
  NULL,
  L"Hujjat ZeroViewda ochilmoqda...",

  /* Translations for language cy */
  L"%s o %s",
  L"Gwall. Methu rhedeg ZeroView",
  L"Gwall: Heb ganfod ZeroView!",
  L"Gwall: Nid oedd modd llwytho'r ddogfen i lawr!",
  NULL,
  NULL,
  NULL,
  L"Agor dogfen yn ZeroView...",
};

const char * const gLanguages[] = {
    "en", "sq", "ar", "am", "az", "eu", "ca", "ca-xv", "cn", "tw",
    "hr", "cz", "dk", "nl", "et", "fi", "fr", "de", "hu", "id",
    "it", "ja", "kr", "ku", "mk", "fa", "pl", "br", "pt", "ro",
    "ru", "sk", "es", "sv", "ta", "tr", "uk", "uz", "cy", NULL
};

// from http://msdn.microsoft.com/en-us/library/windows/desktop/dd318693(v=vs.85).aspx
// those definition are not present in 7.0A SDK my VS 2010 uses
#ifndef LANG_CENTRAL_KURDISH
#define LANG_CENTRAL_KURDISH 0x92
#endif

#ifndef SUBLANG_CENTRAL_KURDISH_CENTRAL_KURDISH_IRAQ
#define SUBLANG_CENTRAL_KURDISH_CENTRAL_KURDISH_IRAQ 0x01
#endif

// note: this index isn't guaranteed to remain stable over restarts, so
// persist gLanguages[index/gTranslationsCount] instead
int GetLanguageIndex(LANGID id)
{
    switch (id) {
#define _LANGID(lang) MAKELANGID(lang, SUBLANG_NEUTRAL)
    case _LANGID(LANG_ENGLISH): return 0;
    case _LANGID(LANG_ALBANIAN): return 8;
    case _LANGID(LANG_ARABIC): return 16;
    case _LANGID(LANG_ARMENIAN): return 24;
    case _LANGID(LANG_AZERI): return 32;
    case _LANGID(LANG_BASQUE): return 40;
    case _LANGID(LANG_CATALAN): return 48;
    case MAKELANGID(LANG_CHINESE, SUBLANG_CHINESE_SIMPLIFIED): return 64;
    case MAKELANGID(LANG_CHINESE, SUBLANG_CHINESE_TRADITIONAL): return 72;
    case _LANGID(LANG_CROATIAN): return 80;
    case _LANGID(LANG_CZECH): return 88;
    case _LANGID(LANG_DANISH): return 96;
    case _LANGID(LANG_DUTCH): return 104;
    case _LANGID(LANG_ESTONIAN): return 112;
    case _LANGID(LANG_FINNISH): return 120;
    case _LANGID(LANG_FRENCH): return 128;
    case _LANGID(LANG_GERMAN): return 136;
    case _LANGID(LANG_HUNGARIAN): return 144;
    case _LANGID(LANG_INDONESIAN): return 152;
    case _LANGID(LANG_ITALIAN): return 160;
    case _LANGID(LANG_JAPANESE): return 168;
    case _LANGID(LANG_KOREAN): return 176;
    case MAKELANGID(LANG_CENTRAL_KURDISH, SUBLANG_CENTRAL_KURDISH_CENTRAL_KURDISH_IRAQ): return 184;
    case _LANGID(LANG_MACEDONIAN): return 192;
    case _LANGID(LANG_FARSI): return 200;
    case _LANGID(LANG_POLISH): return 208;
    case MAKELANGID(LANG_PORTUGUESE, SUBLANG_PORTUGUESE_BRAZILIAN): return 216;
    case _LANGID(LANG_PORTUGUESE): return 224;
    case _LANGID(LANG_ROMANIAN): return 232;
    case _LANGID(LANG_RUSSIAN): return 240;
    case _LANGID(LANG_SLOVAK): return 248;
    case _LANGID(LANG_SPANISH): return 256;
    case _LANGID(LANG_SWEDISH): return 264;
    case _LANGID(LANG_TAMIL): return 272;
    case _LANGID(LANG_TURKISH): return 280;
    case _LANGID(LANG_UKRAINIAN): return 288;
    case _LANGID(LANG_UZBEK): return 296;
    case _LANGID(LANG_WELSH): return 304;
    default: return -1;
#undef _LANGID
    }
}

bool IsLanguageRtL(int index)
{
    return 16 == index || 184 == index || 200 == index;
}
